Feature: Submits guess

  The codebreaker breaks codes generated by code maker.
  For each exact match....

Scenario Outline: submit guess
  Given the secret code is "<code>"
  When I submit a guess "<guess>"
  Then the mark should be "<mark>"

Scenarios: no matches
  | code | guess | mark |
  | 1234 | 6666  |      |

Scenarios: 1 match
  | code | guess | mark |
  | 1234 | 1666  | +    |
  | 1234 | 6166  | -    |

Scenarios: 2 matches
  | code | guess | mark |
  | 1234 | 1266  | ++   |
  | 1234 | 1626  | +-   |
  | 1234 | 6621  | --   |

Scenarios: 3 matches
  | code | guess | mark |
  | 1234 | 1236  | +++  |
  | 1234 | 1263  | ++-  |
  | 1234 | 1623  | +--  |
  | 1234 | 6123  | ---  |

Scenarios: 4 matches
  | code | guess | mark |
  | 1234 | 1234  | ++++ |
  | 1234 | 1243  | ++-- |
  | 1234 | 3124  | +--- |
  | 1234 | 4321  | ---- |

Scenarios: duplicated matches
  | code | guess | mark |
  | 1234 | 1111  | +    |
  | 1234 | 2233  | ++   |
  | 1234 | 1113  | +-   |
  | 1234 | 3111  | --   |



